FROM hashicorp/terraform:light
MAINTAINER "Peter Bamsey <peter.bamsey@gmail.com>"

RUN apk add --no-cache --update make python3 py3-pip py3-virtualenv bash
RUN pip3 install -U pylint

ENTRYPOINT ["terraform"]